[workspace]
members = [
    "axion-core"
]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
ark-groth16 = "0.5"
pqc_dilithium = "0.1"
rs_merkle = "1.4"
wasm-bindgen = "0.2"
